# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-11-22 02:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='XueSheng',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('xs_name', models.CharField(max_length=16)),
                ('xs_age', models.IntegerField(default=1)),
            ],
        ),
    ]
